export const SETCURRENTUSER = 'SETCURRENTUSER'
export const SETSTATIONS = 'SETSTATIONS'
export const SETLOCKS = 'SETLOCKS'
export const RENTING_BIKE_REQUEST = 'RENTING_BIKE_REQUEST'
export const RENTING_BIKE_SUCCESS = 'RENTING_BIKE_SUCCESS'
export const RENTING_BIKE_FAILURE = 'RENTING_BIKE_FAILURE'

